# Generated by Django 6.0.7 on 2026-07-31 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='слаг')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('excerpt', models.CharField(blank=True, help_text='Для карточки в ленте. Пусто — возьмём начало текста.', max_length=300, verbose_name='короткое описание')),
                ('body', models.TextField(verbose_name='текст')),
                ('category', models.CharField(choices=[('news', 'Новость'), ('work', 'Работа в портфолио')], db_index=True, default='news', max_length=16, verbose_name='категория')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='обложка')),
                ('cover_alt', models.CharField(blank=True, help_text='Обязательно, если есть обложка: попадает в alt для скринридеров', max_length=200, verbose_name='описание обложки')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='опубликована')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
                'ordering': ['-published_at', '-id'],
            },
        ),
    ]
