# Generated by Django 6.0.7 on 2026-07-31 04:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название')),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True, verbose_name='слаг')),
                ('service_type', models.CharField(blank=True, choices=[('photo', 'Фотосъёмка'), ('video', 'Видеосъёмка'), ('article', 'Написание статей'), ('design', 'Дизайн')], db_index=True, help_text='Пустое — пометка не участвует в подборе заявок', max_length=16, null=True, verbose_name='вид услуги')),
                ('color', models.CharField(default='#E11D2E', help_text='В виде #RRGGBB. Меняется здесь, без правки кода.', max_length=7, verbose_name='цвет')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='описание')),
                ('is_public', models.BooleanField(default=True, help_text='Скрытая пометка работает для подбора, но не видна на сайте', verbose_name='показывать в профиле')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'пометка',
                'verbose_name_plural': 'пометки',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=160, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='телефон')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('content_manager', 'Контент-менеджер'), ('member', 'Участник')], default='member', max_length=32, verbose_name='роль')),
                ('must_change_password', models.BooleanField(default=True, help_text='Ставится при создании аккаунта и при сбросе пароля', verbose_name='требовать смену пароля')),
                ('is_public', models.BooleanField(default=True, verbose_name='показывать в «Штатниках»')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='о себе')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='аватар')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tags', models.ManyToManyField(blank=True, related_name='users', to='accounts.tag', verbose_name='пометки')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ['full_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
