# Generated by Django 6.0.7 on 2026-07-31 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_number', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='номер')),
                ('client_name', models.CharField(max_length=160, verbose_name='имя клиента')),
                ('client_phone', models.CharField(max_length=32, verbose_name='телефон')),
                ('client_contact_extra', models.CharField(blank=True, max_length=160, verbose_name='другая связь')),
                ('service_type', models.CharField(choices=[('photo', 'Фотосъёмка'), ('video', 'Видеосъёмка'), ('article', 'Написание статей'), ('design', 'Дизайн')], max_length=16, verbose_name='вид услуги')),
                ('description', models.TextField(verbose_name='задача')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='дата съёмки')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='место')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Выполнена'), ('rejected', 'Отклонена')], db_index=True, default='new', max_length=16, verbose_name='статус')),
                ('reject_reason', models.CharField(blank=True, max_length=500, verbose_name='причина отклонения')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='сообщение')),
                ('status', models.CharField(choices=[('pending', 'Ждёт решения'), ('accepted', 'Принят'), ('declined', 'Отклонён')], default='pending', max_length=16, verbose_name='статус')),
                ('decision_comment', models.CharField(blank=True, max_length=500, verbose_name='комментарий к решению')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL, verbose_name='участник')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tickets.request', verbose_name='заявка')),
            ],
            options={
                'verbose_name': 'отклик',
                'verbose_name_plural': 'отклики',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('request', 'member'), name='uq_reply_request_member')],
            },
        ),
    ]
